#%RAML 1.0 DataType

type: object
properties:
  code:
    type:  string
    example: '404'
  message:
    type:  string
    example: 'Cannot find object'
  description:
    type:  string
    example: 'Cannot connect to db due to timeout. Try again later'
    required: false