#%RAML 1.0 Trait
usage: Add to all API resources that have error handling
responses:
  400:
  404:
  405:
  406:
  415:
  500:
    body:
      application/json:
        type: !include ../types/errorStructure.raml